### ISSUE TITLE
MongoDB : notes / readme has invalid connection string

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/helm-charts-databases#12]
Generated connection string in the notes and python snippet are invalid.  
Current output :  
```
'mongodb://user-f2wbnp:dcnwvu5ke7lqtj8mnruc@mongodb-0.mongodb-headless:0,mongodb-1.mongodb-headless:0/defaultdb?authSourcedefaultdb
```  

Expected output :  
```
'mongodb://user-f2wbnp:dcnwvu5ke7lqtj8mnruc@mongodb-0.mongodb-headless:27017,mongodb-1.mongodb-headless:27017/defaultdb
```   

2 errors :  
* Port is 0 instead of 27017  
* `?authSourcedefaultdb` and any additional `?` parameters are forbidden by pymongo (at least in the latest `4.3.3` version) resulting in `pymongo.errors.InvalidURI: MongoDB URI options are key=value pairs.` error

**Comment by ihiverlet** [comment]
It should be fixed, [see](https://github.com/InseeFrLab/helm-charts-databases/pull/48/files#diff-3217843dae138b5270b4a4ce8a9a5238c1c6c5e7ac28d0c336085683f5717a52)
